name:                micromath
version:             0.1.0.0
github:              "davidsd/micromath"
license:             BSD-3-Clause
author:              "David Simmons-Duffin"
maintainer:          "dsd@caltech.edu"
copyright:           "2026 David Simmons-Duffin"
language: GHC2021

extra-source-files:
- README.md

description:         An implementation of a small subset of the Wolfram language in Haskell

dependencies:
- base >= 4.7 && < 5
- containers
- text
- mtl
- megaparsec
- scientific
- parser-combinators

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  micromath-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - micromath

# tests:
#   micromath-test:
#     main:                MicroMath/Test.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - micromath
